[WIP] Moving to running t2 as funcmodel for prune
Held at ValueError:

[22-07-16 10:42:52] {custom_callbacks.py:63} INFO - Epoch Start -- Current level of sparsity: 100.0% sparsity in prune_low_magnitude_dense_6/threshold:0 layer
Traceback (most recent call last):
  File "/Users/tallamjr/github/tallamjr/origin/astronet/astronet/train.py", line 662, in <module>
    training()
  File "/Users/tallamjr/github/tallamjr/origin/astronet/astronet/train.py", line 540, in __call__
    model_for_pruning.fit(
  File "/Users/tallamjr/mambaforge/envs/astronet/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/tallamjr/mambaforge/envs/astronet/lib/python3.8/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1821, in _init_from_args
    raise ValueError(
ValueError: In this `tf.Variable` creation, the initial value's shape ((1,)) is not compatible with the explicitly supplied `shape` argument (()).

	modified:   astronet/train.py