Put 'model.build' inside strategy scope as well
Hoping to fix errors:

ValueError: Trying to create optimizer slot variable under the scope for tf.distribute.Strategy (<tensorflow.python.distribute.mirrored_strategy.MirroredStrategy object at 0x2ae51104d4d0>), which is different from the scope used for the original variable (<tf.Variable 'entry_flow/conv_batch_norm_block/conv1d/kernel:0' shape=(3, 6, 32) dtype=float32, numpy=
Make sure the slot variables are created under the same strategy scope. This may happen if you're restoring from a checkpoint outside the scope

	modified:   astronet/atx/train.py