[HOTFIX] Fix ValueError, incompatiable shape
Hopefully this change should allow for Concatenate layer to do calculation

Error:
    ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 2), (None, 100, 32)]

Refs:
    - https://www.tensorflow.org/api_docs/python/tf/broadcast_to
	modified:   astronet/t2/model.py