Allow for use of custom log loss metric in 2.3.1
Since experimental.numpy api seems to only be available from 2.4.x
onwards, these changes allow for use of numpy operations to compute a
custom metric.

Note this was previously failing because of model.compile requiring
'run_eagerly=True' to be set.

Error:

    TF 2.0 'Tensor' object has no attribute 'numpy' while using .numpy() although eager execution enabled by default

    TF 2.0 Custom Metric 'Tensor' object has no attribute 'numpy'

Furthermore, a simple transition to tensorflow operations such as
+    # wtable = tf.reduce_sum(y_true, axis=0) / y_true.shape[0]
did not work and would through errors relating to:

Error:
E         ValueError: in user code:
E                 raise ValueError("None values not supported.")
E
E             ValueError: None values not supported.

Refs:
    - https://github.com/tensorflow/tensorflow/issues/35393
    - https://github.com/tensorflow/tensorflow/issues/27519

	modified:   astronet/metrics.py
	modified:   astronet/t2/tests/int/test_train.py