Attempt to resolve OSError with loading tf model
OSError:

    File "/usr/local/anaconda3/envs/astronet/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
      constants.SAVED_MODEL_FILENAME_PB))
    OSError: SavedModel file does not exist at: /Users/tallamjr/github/tallamjr/origin/astronet/astronet/t2/models/model-1601422759-68fcd4d/saved_model.pb/{saved_model.pbtxt|saved_model.pb}

Refs:
    - https://github.com/tensorflow/tensorflow/issues/33474#issuecomment-551409539

	modified:   train.py