Fix version to 1.19.2 due to pip error
    ERROR: Could not install packages due to an EnvironmentError: [Errno 2]
    No such file or directory:
    '/usr/local/anaconda3/envs/astronet/lib/python3.7/site-packages/numpy-1.19.2.dist-info/METADATA'

	modified:   requirements.txt