Refactor loop so that self.num_layers not required
This should resolve the following error:

Error:
    E         AttributeError: in user code:
    E
    E             /usr/local/anaconda3/envs/astronet/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:808 train_function  *
    E                 return step_function(self, iterator)
    E             /Users/tallamjr/github/tallamjr/origin/astronet/astronet/t2/model.py:46 call  *
    E                 for layer in range(self.num_layers):
    E
    E             AttributeError: 'T2Model' object has no attribute 'num_layers'

Refs:
    - https://www.coursera.org/learn/custom-models-layers-loss-functions-with-tensorflow/lecture/Dv4Ub/understanding-residual-networks

	modified:   astronet/t2/model.py