[WIP] Adding keras implementation of LogLoss
Note, for custom loss, tensorflow require operation act on tensors and
not numpy functions. Otherwise the follow error occurs.

Error:
    NotImplementedError: Cannot convert a symbolic Tensor (IteratorGetNext:1) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

Refs:
    - https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy

Further Refs:
    > Multi-weight logloss for keras
        - https://www.kaggle.com/c/PLAsTiCC-2018/discussion/69795
    > Custom loss function in Keras
        - https://stackoverflow.com/questions/43818584/custom-loss-function-in-keras
    > Difference between Tensorflow and Scikitlearn log_loss function implementation
        - https://stackoverflow.com/questions/42658464/difference-between-tensorflow-and-scikitlearn-log-loss-function-implementation
    > Custom losses
        - https://www.tensorflow.org/guide/keras/train_and_evaluate#custom_losses
    > What is the difference between cross-entropy and log loss error?
        - https://stackoverflow.com/questions/50913508/what-is-the-difference-between-cross-entropy-and-log-loss-error

	modified:   constants.py
	modified:   evaluate.py
	modified:   utils.py