[CI] Updating requirements due to Actions Error
Error:
    ERROR: Could not find a version that satisfies the requirement jupyter-console>=6.1.0 (from astronet==0.1.dev1+gb260508) (from versions: 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0, 4.1.1, 5.0.0b1, 5.0.0, 5.1.0, 5.2.0)
    ERROR: No matching distribution found for jupyter-console>=6.1.0 (from astronet==0.1.dev1+gb260508)

	modified:   requirements.txt