Fix for failing test due to update to API
Error:

    ModuleNotFoundError                       Traceback (most recent call last)
    ~/work/astronet/astronet/astronet/t2/train.py in <module>
    ----> 1 from astronet.t2.visuals import *

    ModuleNotFoundError: No module named 'astronet.t2.visuals'

	modified:   notebooks/T2-Mini-Analysis-Pipeline.ipynb