Fix ValueError when broadcasting to x
ValueError: Tried to convert 'shape' to a tensor and failed. Error: Cannot convert a partially known TensorShape to a Tensor: (None, 100, 32)

* tf.shape and Tensor.shape should be identical in eager mode. Within tf.function or within a
compat.v1 context, not all dimensions may be known until execution time. Hence when defining
custom layers and models for graph mode, prefer the dynamic tf.shape(x) over the static x.shape.

Note: When using symbolic tensors, such as when using the Keras API, tf.shape() will return the
shape of the symbolic tensor.

Refs:
    - https://github.com/huggingface/transformers/issues/1962
    - https://www.tensorflow.org/api_docs/python/tf/shape

	modified:   astronet/t2/transformer.py